defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: libero-goal-lewm-v0
  num_envs: 1
  max_episode_steps: 50
  history_size: 3
  frame_skip: 1
  goal_conditioned: True
  demo_hdf5_path: /root/autodl-tmp/stable-wm/libero_goal.h5
  task_id: 0

dataset:
  keys_to_cache:
    - action
    - proprio

seed: 42
policy: /root/autodl-tmp/stable-wm/outputs/lewm_libero_goal_epoch_97

plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 1

eval:
  num_eval: 5
  img_size: 224
  dataset_name: libero_goal
  goal_offset: 10
  max_steps: 50
